from ingestion.loadfiles import load_files
from chunking.split import split_documents_recursively , split_docs_semantic
from embeddings.embed import embed_documents
from retrieval.retriever import get_plant_retriver
from generation.llm_generation import generate_content, format_docs
from evaluation.evals import run_evals 


def rag_pipeline():
    ## STEP 1 - Load files and convert to documents 
    documents = load_files() 
    print(f"Step 1 - Files are loaded and converted to documents. Total documents: {len(documents)}")

    #print("Chunking now")
    #chunks = split_documents_recursively(documents)
    #print(f"Step 2 - Documents are chunked Recursively Total chunks: {len(chunks)}")
    ##print(chunks)

    print("Chunking semantically")
    semantic_chunks = split_docs_semantic(documents)
    print(f"Step 2 - Documents are chunked Semantically Total chunks: {len(semantic_chunks)}")

    #print(semantic_chunks)

    """
    Observation from Semantic chunks :
    broke the context window in Chunks 5 and 6 and left Chunk 3 as a massive text dump.
    chunk 1 & 2 - good 
    chunk 3 - massive table dump( problematic for large tables)
    chunk 4 - good 
    chunk 5 & 6 - broke the context window and left a lot of text out of the chunks for chunk 5 and shifted to chunk 6 

    So, we could use Recursive and Semantic chunking together to get the best of both worlds.
    """

    ## Moving to store embeddings in vector dbs 
    print("Embeddings are generating now")
    vectorstore = embed_documents(semantic_chunks)
    print("Step 3 - Documents embedded and stored in Chroma")

   ## Move to step 4 - Getting relevant chunk according to the question invoked
    user_query = input("Please enter your question about plants: ").strip()
    plant_retriever = get_plant_retriver(vectorstore)

    ##get relevant chunks from the vectorstore
    relevant_chunks = plant_retriever.invoke(user_query)

    print(f"Step 4 - Retrieved relevant chunks from the vectorstore for the question: {len(relevant_chunks)}")
    #print(relevant_chunks)

    ## MOve to step 5 - concatenate the content first
    context = format_docs(relevant_chunks)
    print(f"Step 5 - Concatenated the content of the retrieved chunks for the prompt context. Total length of context: {len(context)} characters")

    print(f"Context: {context}")

    ## MOve to step 6 
    final_output = generate_content(user_query, plant_retriever)
    print(f"Step 6 - Final output generated by the LLM: {final_output}")

    ## Move to step 7 - Evaluate the final output
    evaluation_result = run_evals(user_query, context, final_output)
    print(f"Step 7 - Evaluation result: {evaluation_result}")


if __name__ == "__main__":
    rag_pipeline() 